services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: website-ylm-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - app_network
        depends_on:
            - db

    db:
        image: mysql:9
        container_name: website-ylm-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app_network

    nginx:
        image: nginx:alpine
        container_name: website-ylm-nginx
        restart: unless-stopped
        ports:
            - '80:80'
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - app_network
        depends_on:
            - app

networks:
    app_network:
        driver: bridge

volumes:
    dbdata:
